# Default values for rotisserie.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Images

# the repository URL for the image
imageRepository:
# the tag for the image version being used
imageTag:

## Ingress

# list used for single or multiple hostnames. if using multiple
# hostnames add a new host under the current host in the format
# - example.com
ingress:
  hostnames:
    -

## Secrets

# Specify secrets for the rotisserie-app.
secrets:
  token:
  clientID:

# Specify the email and hostname for kube-lego.
certManager:
  email:
  url: https://acme-v01.api.letsencrypt.org/directory
