---
apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-ocr
spec:
  ports:
  - port: 3001
    protocol: TCP
    name: pubgredzone-ocr
  selector:
    app: pubgredzone-ocr
---
apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: pubgredzone-app
  selector:
    app: pubgredzone-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-app
spec:
  template:
    metadata:
      labels:
        app: pubgredzone-app
    spec:
      containers:
        - name: pubgredzone-app
          image: container-registry.dev.ibmesports.com/pubgredzone-app:latest
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: pubgredzone
                key: api-key
          ports:
            - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-ocr
spec:
  template:
    metadata:
      labels:
        app: pubgredzone-ocr
    spec:
      containers:
        - name: pubgredzone-ocr
          image: container-registry.dev.ibmesports.com/pubgredzone-ocr:latest
          ports:
            - containerPort: 3001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pubgredzone-ingress
spec:
  tls:
    - hosts: 
      - pubgred.zone
      secretName: pubgredzone
  rules:
  - host: pubgredzone.ibmesports.com
    http:
      paths:
      - path: /
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
      - path: /process_pubg
          serviceName: pubgredzone-ocr
          servicePort: 3001
  - host: pubgred.zone
    http:
      paths:
      - path: /
        backend:
          serviceName: pubgredzone-app
          servicePort: 3000
